name: faboules
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.4.1 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  nowplaying: ^3.0.3
  provider: ^6.1.2
  dio: ^5.7.0
  html: ^0.15.4
  google_fonts: ^6.2.1
  translator: ^1.0.0
  spotify: ^0.13.7
  palette_generator: ^0.3.3+4
  url_launcher: ^6.3.0
  entry: ^1.0.0
#  flutter_launcher_icons:

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

# flutter pub run flutter_launcher_icons:main
# "WARNING: Icons with alpha channel are not allowed in the Apple App Store.
# Set "remove_alpha_ios: true" to remove it."
flutter_icons:
  android: "launcher_icon"
  remove_alpha_ios: true
  ios: true
  image_path: "assets/logo_ios.png"


flutter:
  uses-material-design: true

  assets:
    - assets/
